### ISSUE TITLE
Add function to use as many password strength bar as needed by the user.

### ISSUE THREAD

**Issue by thenishchalraj** [nishchalraj/PasswordStrengthBar#4]
This feature is needed to be build by someone who knows how recycler view works and create functions/methods for numbers of bars and their colours. Interesting thing is, user can input the number of password strength bar that he needs (default is 4) and respective colour and they should get mapped accordingly.

**Comment by Algure** [comment]
I'd like to work on this

**Comment by rahullli** [comment]
I would like to work on this issue.

**Comment by thenishchalraj** [comment]
@Algure and @rahullli it's nice that you guys showed your interest. If you are confident then surely you can contribute to this. I would merge after the review.

**Comment by charchitmangal** [comment]
hello i would like to work on this, pls assign me

**Comment by crazyvibes** [comment]
Hi I'd like to work on this.

**Comment by Madhusudhanv7** [comment]
Hi I'd like to work on this.

**Comment by rahullli** [comment]
I am already working on this issue .

**Comment by rahullli** [comment]
> This feature is needed to be build by someone who knows how recycler view works and create functions/methods for numbers of bars and their colours. Interesting thing is, user can input the number of password strength bar that he needs (default is 4) and respective colour and they should get mapped accordingly.

I have opened the app but it is already showing the password strength bars on typing the password , so can you please tell more what should I have to  do .

**Comment by thenishchalraj** [comment]
Hey @rahullli I think you didn't get what is this and how it works. I did some findings and I think I should start assigning things so this will go to @crazyvibes and you can take up any other issue that comes in the future. Or you may think of adding some features to this library.

**Comment by crazyvibes** [comment]
Thank you very much @thenishchalraj

**Comment by thenishchalraj** [comment]
Cool. You can complete it by 3-5 of this month. Or if any other date we can discuss. @crazyvibes

**Comment by crazyvibes** [comment]
Sure @thenishchalraj

**Comment by thenishchalraj** [comment]
You're on it @crazyvibes ? Haven't seen any update.

**Comment by crazyvibes** [comment]
@thenishchalraj  I am on it

**Comment by crazyvibes** [comment]
I need one more day to work on it @thenishchalraj

**Comment by crazyvibes** [comment]
I am trying to set number of strength bars and their color programatically.

**Comment by crazyvibes** [comment]
very close to fixing this issue:)
